# Generated by Django 3.2.7 on 2021-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210311_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
