# Generated by Django 3.2.7 on 2021-10-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(max_length=400, null=True),
        ),
    ]
