# Generated by Django 3.2.7 on 2021-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_frecuente_si_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateField()),
                ('hora_salida', models.DateField()),
                ('placa', models.CharField(max_length=6)),
                ('nombre_administrativo', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.IntegerField(choices=[(1, 'Camioneta'), (2, 'Motocarro'), (3, 'Automovil'), (4, 'Motocicleta'), (5, 'Bus'), (6, 'Camion')])),
                ('frecuente_si_no', models.BooleanField()),
            ],
        ),
    ]
