# Generated by Django 3.2.7 on 2021-09-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20210923_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='precio_estadar_tipo_vehiculo',
            new_name='total_vehiculo',
        ),
    ]
