# Generated by Django 3.2.7 on 2021-09-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20210923_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_administrador', models.CharField(max_length=20)),
                ('ubicacion', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'A6'), (7, 'A7'), (8, 'A8'), (9, 'A9'), (10, 'A10'), (11, 'A11'), (12, 'A12'), (13, 'A13'), (14, 'A14'), (15, 'A15'), (16, 'A16'), (17, 'A17'), (18, 'A18'), (19, 'A19'), (20, 'A20')], verbose_name='Ubicacion parqueadero')),
                ('gastos_totales', models.FloatField()),
                ('placa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.factura')),
            ],
            options={
                'verbose_name': 'parqueadero',
                'verbose_name_plural': 'parqueaderos',
            },
        ),
    ]
