# Generated by Django 3.2.7 on 2021-09-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_parqueadero'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='hora_puesto',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='hora_puesto_exit',
            field=models.TimeField(null=True),
        ),
    ]
