# Generated by Django 3.2.7 on 2021-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20210927_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parqueadero',
            options={'verbose_name': 'parqueos', 'verbose_name_plural': 'parqueaderos'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(verbose_name='cedula'),
        ),
    ]
