# Generated by Django 3.2.7 on 2021-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puestos_totales', models.IntegerField()),
                ('puestos_llenos', models.IntegerField()),
                ('puestos_vacios', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Puesto',
            },
        ),
        migrations.AlterModelOptions(
            name='parqueadero',
            options={'verbose_name': 'parqueo'},
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='hora_puesto',
            field=models.TimeField(null=True, verbose_name='Hora de llegada'),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='hora_puesto_exit',
            field=models.TimeField(null=True, verbose_name='Hora de salida'),
        ),
    ]
