# Generated by Django 3.2.7 on 2021-10-06 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_parqueadero_hora_puesto_exit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='placa',
        ),
        migrations.AddField(
            model_name='factura',
            name='placa_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='placa_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.vehiculo'),
        ),
    ]
