# Generated by Django 3.2.7 on 2021-10-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0018_auto_20211005_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puestos_totales', models.IntegerField()),
                ('puestos_llenos', models.IntegerField()),
                ('puestos_vacios', models.IntegerField()),
                ('ubicacion', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'A6'), (7, 'A7'), (8, 'A8'), (9, 'A9'), (10, 'A10'), (11, 'A11'), (12, 'A12'), (13, 'A13'), (14, 'A14'), (15, 'A15'), (16, 'A16'), (17, 'A17'), (18, 'A18'), (19, 'A19'), (20, 'A20')], null=True, verbose_name='Ubicacion parqueadero')),
            ],
            options={
                'verbose_name': 'Puesto',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField()),
                ('placa', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.IntegerField(choices=[(1, 'Camioneta'), (2, 'Motocarro'), (3, 'Automovil'), (4, 'Motocicleta'), (5, 'Bus'), (6, 'Camion')], verbose_name='Tipo de vehiculo')),
                ('modelo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('cilindraje', models.CharField(max_length=40)),
                ('placa', models.CharField(max_length=6, null=True)),
                ('dueño_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_administrador', models.CharField(max_length=20)),
                ('ubicacion', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'A6'), (7, 'A7'), (8, 'A8'), (9, 'A9'), (10, 'A10'), (11, 'A11'), (12, 'A12'), (13, 'A13'), (14, 'A14'), (15, 'A15'), (16, 'A16'), (17, 'A17'), (18, 'A18'), (19, 'A19'), (20, 'A20')], verbose_name='Ubicacion parqueadero')),
                ('gastos_totales', models.FloatField()),
                ('hora_puesto', models.TimeField(null=True, verbose_name='Hora de llegada')),
                ('hora_puesto_exit', models.TimeField(verbose_name='Hora de salida')),
                ('placa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.vehiculo')),
            ],
            options={
                'verbose_name': 'parqueo',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('nombre_administrativo', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.IntegerField(choices=[(1, 'Camioneta'), (2, 'Motocarro'), (3, 'Automovil'), (4, 'Motocicleta'), (5, 'Bus'), (6, 'Camion')])),
                ('total_vehiculo', models.IntegerField(choices=[(1, '4000'), (2, '4000'), (3, '3500'), (4, '2000'), (5, '5000'), (6, '8000')], null=True)),
                ('frecuente_si_no', models.BooleanField()),
                ('dueño_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('placa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.vehiculo')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
    ]
